
export type ICashFlow = {
    capitalExpenditures: number,
    cashChange: number,
    cashFlow: number,
    cashFlowFinancing: number,
    changesInInventories: number,
    changesInReceivables: number,
    currency: string,
    date: number,
    depreciation: number,
    dividendsPaid: boolean,
    exchangeRateEffect: boolean,
    filingType: string,
    fiscalDate: string,
    fiscalQuarter: number,
    fiscalYear: number,
    id: string,
    investingActivityOther: boolean,
    investments: boolean,
    key: string,
    netBorrowings: number,
    netIncome: number,
    otherFinancingCashFlows: boolean,
    reportDate: string,
    subkey: string,
    symbol: string,
    totalInvestingCashFlows: number,
    updated: number
}


export type IQuote = {
    avgTotalVolume: number
    calculationPrice: string
    change: number
    changePercent: number
    close: number
    closeSource: string
    closeTime: number
    companyName: string
    currency: string
    delayedPrice: number
    delayedPriceTime: number
    extendedChange: number
    extendedChangePercent: number
    extendedPrice: number
    extendedPriceTime: number
    high: number
    highSource: string
    highTime: number
    iexAskPrice: boolean
    iexAskSize: boolean
    iexBidPrice: boolean
    iexBidSize: boolean
    iexClose: number
    iexCloseTime: number
    iexLastUpdated: null
    iexMarketPercent: null
    iexOpen: 182.9
    iexOpenTime: 1680787800391
    iexRealtimePrice: null
    iexRealtimeSize: null
    iexVolume: null
    isUSMarketOpen: false
    lastTradeTime: number
    latestPrice: number
    latestSource: string
    latestTime: string
    latestUpdate: number
    latestVolume: number
    low: number
    lowSource: string
    lowTime: number
    marketCap: number
    oddLotDelayedPrice: number
    oddLotDelayedPriceTime: number
    open: number
    openSource: string
    openTime: number
    peRatio: number
    previousClose: number
    previousVolume: number
    primaryExchange: string
    symbol: string
    volume: number
    week52High: number
    week52Low: number
    ytdChange: number
}